apiVersion: apps/v1
kind: Deployment
metadata:
  name: rideprice-api
  labels:
    app: rideprice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rideprice
  template:
    metadata:
      labels:
        app: rideprice
    spec:
      containers:
        - name: api
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"